#!/usr/bin/env python

Import('env')


env.Append(CPPPATH = [
	'#main',
	'#thirdparty/glad/include',
	'#thirdparty/glad/src',
	'#thirdparty/glfw/include',
	'#thirdparty/glm',
])

env.source = Glob("#main/*.cpp") + Glob("#thirdparty/glad/src/*.c")
