#!/usr/bin/env python

# Program("Vker", Glob('*.cpp'));

import os

platform = ARGUMENTS.get('p','Linux');


# build params
vars = Variables('custom.py',ARGUMENTS)
vars.Add(ListVariable('p', 'you want to build platform(default: windows)', 'Linux',
                    ['Windows', 'Linux', 'MacOX']))
vars.Add(ListVariable('bits', 'you want to build platform(default: 64)', 'x86_64',
                    ['x86_64', 'x86', 'x64']))

# 64 bit
env = Environment(variables = vars, TARGET_ARCH="${bits}")
vars.Update(env)
Help(vars.GenerateHelpText(env))

# scons config
env.Decider("MD5-timestamp")
env.SetOption("implicit_cache", 1)

# project
dir_main = Glob("./*.cpp")

# project config

env.Append(CPPDEFINES = ['Vker'])

env.Program("bin/Vker_${bits}_debug", dir_main);
