#!/usr/bin/env python

# Program("Vker", Glob('*.cpp'));

import os

env = Environment(TARGET_ARCH="x86_64")

# scons config
env.Decider("MD5-timestamp")
env.SetOption("implicit_cache", 1)

# project
dir_main = Glob("./*.cpp") + Glob("./thirdparty/glad/src/*.c")

env.Append(CPPPATH = [
    "./thirdparty/glad/include",
    "./thirdparty/glad/src",
])

# -lGLEW -lglfw3 -lGL -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread

env.Append(LIBS = ["libglfw3", "GL", "dl", "libX11.so", "libpthread.so","libXxf86vm.so", "libXrandr.so", "libXi.so", "libXinerama.so", "libXcursor.so"]);

# env.Append(CXXFLAGS = ["-lX11"])
env.Program("Vker", dir_main);
